# Copyright 2022 Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

# This workflow is for ongoing seL4/AArch64 verification.

name: AArch64 Proofs

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
    branches:
      - aarch64
  # this action needs access to secrets.
  # The actual test runs in a no-privilege VM, so it's Ok to run on untrusted PRs.
  pull_request_target:
    paths-ignore:
      - '**.md'
      - '**.txt'
    branches:
      - aarch64

jobs:
  all:
    name: All
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [AARCH64]
    # test only most recent push to PR:
    concurrency: l4v-pr-${{ github.event.number }}-idx-${{ strategy.job-index }}
    steps:
    - name: Proofs
      uses: seL4/ci-actions/aws-proofs@master
      with:
        L4V_ARCH: ${{ matrix.arch }}
        token: ${{ secrets.READ_TOKEN }}
        cache_bucket: ${{ secrets.CACHE_BUCKET }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SSH: ${{ secrets.AWS_SSH }}
        GH_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
    - name: Upload logs
      uses: actions/upload-artifact@v2
      with:
        name: logs-${{ matrix.arch }}
        path: logs.tar.xz
